//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication007.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModuleDetail()
        {
            this.Permissions = new HashSet<Permission>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string Title { get; set; }
        public string Page_Name { get; set; }
        public string default_url { get; set; }
        public Nullable<bool> IsParent { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Module Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}
