//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication007.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int PermissionID { get; set; }
        public Nullable<int> ModulePermissionID { get; set; }
        public Nullable<int> ModuleDetailID { get; set; }
        public Nullable<bool> Allow_Insert { get; set; }
        public Nullable<bool> Allow_Update { get; set; }
        public Nullable<bool> Allow_Delete { get; set; }
        public Nullable<bool> Allow_View { get; set; }
        public Nullable<bool> Allow_Approval { get; set; }
    
        public virtual ModuleDetail ModuleDetail { get; set; }
        public virtual ModuleRolePermission ModuleRolePermission { get; set; }
    }
}
