//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication007.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PO_Detail()
        {
            this.Shipment_Detail = new HashSet<Shipment_Detail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PO_ID { get; set; }
        public Nullable<int> Item_Code { get; set; }
        public Nullable<int> XS_Qty { get; set; }
        public Nullable<int> S_Qty { get; set; }
        public Nullable<int> M_Qty { get; set; }
        public Nullable<int> L_Qty { get; set; }
        public Nullable<int> XL_Qty { get; set; }
        public Nullable<int> C2XL_Qty { get; set; }
        public Nullable<int> C3XL_Qty { get; set; }
        public string Remarks { get; set; }
    
        public virtual ItemMaster ItemMaster { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shipment_Detail> Shipment_Detail { get; set; }
    }
}
