//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication007.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_WIP
    {
        public int ID { get; set; }
        public Nullable<int> PO_ID { get; set; }
        public Nullable<int> PO_DetailID { get; set; }
        public string CTL { get; set; }
        public string PO_Print { get; set; }
        public string Yarn { get; set; }
        public string Kni { get; set; }
        public string Dying { get; set; }
        public string Cutting { get; set; }
        public string Swing { get; set; }
        public string Checking { get; set; }
        public string Pressing { get; set; }
        public string Packing { get; set; }
        public string Units { get; set; }
        public string Mode { get; set; }
        public string Remarks { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
