//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication007.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment_Detail
    {
        public int ShipmentID { get; set; }
        public Nullable<int> ContainerNumber { get; set; }
        public Nullable<int> PO_DetailID { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<int> XS_Qty { get; set; }
        public Nullable<int> S_Qty { get; set; }
        public Nullable<int> M_Qty { get; set; }
        public Nullable<int> L_Qty { get; set; }
        public Nullable<int> XL_Qty { get; set; }
        public Nullable<int> C2XL_Qty { get; set; }
        public Nullable<int> C3XL_Qty { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Composit { get; set; }
        public string Trim_Approved { get; set; }
        public string Comments { get; set; }
    
        public virtual PO_Detail PO_Detail { get; set; }
    }
}
